# This release process looks for dim-web tags and produces releases
# build on the version number.
name: release_dim-web

on:
  push:
    tags:
      - 'dim-web-*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    container:
      image: debian:10
      env:
        _VERSION: ${{ needs.build.outputs.version }}

    steps:
      - run: echo "::set-output name=version::$(echo "$_REF" | cut -d'-' -f2-)"
        id: version
        shell: bash
        env:
          _REF: ${{ github.ref }}
      - run: apt-get update
      - run: apt-get install --yes npm
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: dim-web
      - run: npm run build
        working-directory: dim-web
      - run: dist/index.html
        working-directory: dim-web
      - run: tar --transform="s,^dim-web/,dim-web-${_version}/," -czvf "dim-web-src-${_version}.tar.gz" dim-web
        env:
          _version: ${{ steps.version.outputs.version }}
      - uses: actions/upload-artifact@v2
        with:
          name: dim-web-src-${{ steps.version.outputs.version }}.tar.gz
          path: dim-web-src-${{ steps.version.outputs.version }}.tar.gz
